# Samplesheet for sample demultiplexing and file naming.
samplesheet: "config/mini_samplesheet.txt" #samplesheet-Hremoved.txt"
indices: "config/indexfordemux.txt"
fastqlist: "config/mini_fastqlist.txt"
lenR1primer: "23"
lenR2primer: "24"
lenR1index: "7"
lenR2index: "7"

# Input directories.
fastqdir: ""
demux: "workflow/rules/demux.sh"

# Output directories.
demuxdir: "workflow/out/demux"
trimdir: "workflow/out/trimmed"
outdir: "workflow/out/"
